volumes:
  dbdata:

services:
  db: 
    image: mysql:9.1.0
    # restart: always
    healthcheck:
      test: "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD}"
      interval: 1s
      retries: 50
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
  
  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

  backend:
    build: ./src
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

