services:
  db: 
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=bob
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./src
    ports:
      - 8000:8000

volumes:
  dbdata: