volumes:
  primary_data:
#   messageData:

services:
  pubsub:
    image: redis
    container_name: redisPubSub

  primary_db:
    image: mysql:9.1.0
    container_name: primary_db
    healthcheck:
      test: "out=$$(mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }"
      interval: 1s
      retries: 50
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - primary_data:/var/lib/mysql
    command: >
      bash -c '
      echo "CREATE DATABASE IF NOT EXISTS $DB_NAME_TEST;
      GRANT ALL ON \`${DB_NAME_TEST}%\`.* TO \`$DB_USER\`@\`%\`;" > /docker-entrypoint-initdb.d/createTestDB.sql;
      docker-entrypoint.sh mysqld
      '
    
  primary_service:
    build:
      context: src
    container_name: primary_service
    depends_on:
      primary_db:
        condition: service_healthy
      pubsub:
        condition: service_started
    ports: 
      - 8080:8080
    # restart: always
    environment:
      PS_HOST: pubsub
      EMAIL_CHANNEL: ${EMAIL_CHANNEL}
      DB_HOST: primary_db
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: 3306
      DEFAULT_USERNAME: ${DEFAULT_USERNAME}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}

  primary_test:
    build: 
      context: src
      dockerfile: test.Dockerfile
    container_name: primary_service_test
    profiles:
      - test
    depends_on: 
      primary_db:
        condition: service_healthy
    environment:
      DB_HOST: primary_db
      MYSQL_DATABASE: ${DB_NAME_TEST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: 3306
    volumes: 
      - ./coverage:/app/coverage

  email_service:
    build:
      context: services/emailing
    container_name: email_service
    depends_on:
      primary_service:
        condition: service_started
      pubsub:
        condition: service_started
    # restart: always
    environment:
      PS_HOST: pubsub
      EMAIL_CHANNEL: ${EMAIL_CHANNEL}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_SENDER: ${EMAIL_SENDER}

  # user_recieve:
  #   build:
  #     context: users
  #   restart: always
  #   environment:
  #     PS_HOST: pubsub
  #   command: ["2", "1"]

  # receiver2:
  #   build:
  #     context: users
  #   restart: always
  #   environment:
  #     PS_HOST: pubsub
  #   command: ["2", "1"]
  #
  # receiver3:
  #   build:
  #     dockerfile: database/Dockerfile
  #     # context: database
  #   restart: always
  #   environment:
  #     PS_HOST: pubsub
  #   command: ["2", "1"]

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #
  # # User section
  # userDB: 
  #   image: mysql:9.1.0
  #   healthcheck:
  #     test: "mysqladmin ping -h localhost --silent"
  #     interval: 1s
  #     retries: 50
  #     start_period: 5s
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #   volumes:
  #     - userData:/var/lib/mysql
  # 
  # userApi:
  #   build: ./database
  #   environment:
  #     DB_HOST: db
  #   depends_on:
  #     userDB:
  #       condition: service_healthy
  #   ports:
  #     - 8000:8000
  #
  # # Message section
  # messageDB:
  #   image: mysql:9.1.0
  #   healthcheck:
  #     test: "mysqladmin ping -h localhost --silent"
  #     interval: 1s
  #     retries: 50
  #     start_period: 5s
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #   volumes:
  #     - messageData:/var/lib/mysql
  #
  # messageApi:
  #   build: ./message
  #   environment:
  #     DB_HOST: db
  #   depends_on:
  #     messageDB:
  #       condition: service_healthy
  #   ports:
  #     - 8000:8000
